repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: golangci-lint
    - id: go-build
    - id: go-mod-tidy
- repo: local
  hooks:
    - id: local-build
      name: Locally build
      description: A local make file to always build and test locally
      entry: make build
      language: system
      types: [bash]
